version: "3"
services:
  app:
    container_name: app
    build: .
    ports:
        - "8080:8080"
    links:
        - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
        - "27017:27017"